=== nirbhayph/Fandango-XML/02/fandango.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:element name="Fandango">
  <xsd:complexType>
    <xsd:sequence>
      <xsd:element name="CompanyName" type="xsd:string"/>
      <xsd:element name="Date" type="xsd:date"/>
      <xsd:element name="Location" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="City" type="xsd:string"/>
            <xsd:element name="StateCode" type="xsd:string"/>
            <xsd:element name="Theater" maxOccurs="unbounded">
              <xsd:complexType>
                <xsd:sequence>
                <xsd:element name="Name" type="xsd:string"/>
                <xsd:element name="Address">
                  <xsd:complexType>
                    <xsd:sequence>
                    <xsd:element name="Street" type="xsd:string"/>
                    <xsd:element name="Zip" type="xsd:string"/>
                  </xsd:sequence>
                  </xsd:complexType>
                </xsd:element>
                <xsd:element name="Note" type="xsd:string"/>
                <xsd:element name="Movies">
                  <xsd:complexType>
                    <xsd:sequence>
                    <xsd:element name="Movie" maxOccurs="unbounded">
                      <xsd:complexType>
                      <xsd:sequence>
                      <xsd:element name="Title" type="xsd:string"/>
                      <xsd:element name="Duration" type="xsd:string"/>
                      <xsd:element name="Time" maxOccurs="unbounded">
                        <xsd:complexType mixed="true">
                          <xsd:attribute name="type" use="required">
                            <xsd:simpleType>
                              <xsd:restriction base="xsd:string">
                                <xsd:enumeration value="morning"/>
                                <xsd:enumeration value="afternoon"/>
                                <xsd:enumeration value="evening"/>
                                <xsd:enumeration value="night"/>
                              </xsd:restriction>
                            </xsd:simpleType>
                          </xsd:attribute>
                        </xsd:complexType>
                      </xsd:element>
                      <xsd:element name="MovieCategory">
                        <xsd:simpleType>
                          <xsd:restriction base="xsd:string">
                            <xsd:enumeration value="(R)"/>
                            <xsd:enumeration value="(PG)"/>
                            <xsd:enumeration value="(PG-13)"/>
                          </xsd:restriction>
                        </xsd:simpleType>
                      </xsd:element>
                      <xsd:element name="NewLabel">
                        <xsd:simpleType>
                          <xsd:restriction base="xsd:string">
                            <xsd:enumeration value="Yes"/>
                            <xsd:enumeration value="No"/>
                          </xsd:restriction>
                        </xsd:simpleType>
                      </xsd:element>
                      <xsd:element name="ClosedCaption">
                        <xsd:simpleType>
                          <xsd:restriction base="xsd:string">
                            <xsd:enumeration value="Yes"/>
                            <xsd:enumeration value="No"/>
                          </xsd:restriction>
                        </xsd:simpleType>
                      </xsd:element>
                      <xsd:element name="NoPasses">
                        <xsd:simpleType>
                          <xsd:restriction base="xsd:string">
                            <xsd:enumeration value="Yes"/>
                            <xsd:enumeration value="No"/>
                          </xsd:restriction>
                        </xsd:simpleType>
                      </xsd:element>
                      <xsd:element name="AdditionDetails" type="xsd:string" minOccurs="0"/>
                      <xsd:element name="Language" type="xsd:string"/>
                  </xsd:sequence>
                  </xsd:complexType>
                </xsd:element>
              </xsd:sequence>
              </xsd:complexType>
            </xsd:element>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== nirbhayph/Fandango-XML/02/fandango.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="fandango.css"?>
<Fandango xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="fandango.xsd">
	<CompanyName>FANDANGO</CompanyName>
	<Date>2018-09-26</Date>
	<Location>
		<City>Rochester</City>
		<StateCode>NY</StateCode>
		<Theater>
			<Name>Movies 10</Name>
			<Address>
				<Street>West Henrietta Road</Street>
				<Zip>14623</Zip>
			</Address>
			<Note>Text to FNDGO (36346) from your wireless device to get this theater's showtimes.</Note>
			<Movies>
				<Movie>
					<Title>The Happytime Murders</Title>
					<Duration>1 hr 31 min</Duration>
					<Time type="afternoon">12:25:00</Time>
					<Time type="evening">17:45:00</Time>
					<Time type="evening">19:50:00</Time>
					<MovieCategory>(R)</MovieCategory>
					<NewLabel>No</NewLabel>
					<ClosedCaption>No</ClosedCaption>
					<NoPasses>No</NoPasses>
					<Language>English</Language>
				</Movie>
				<Movie>
					<Title>Alpha</Title>
					<Duration>1 hr 37 min</Duration>
					<Time type="afternoon">12:20:00</Time>
					<Time type="afternoon">14:35:00</Time>
					<Time type="evening">16:50:00</Time>
					<Time type="evening">19:15:00</Time>
					<MovieCategory>(PG-13)</MovieCategory>
					<NewLabel>No</NewLabel>
					<ClosedCaption>No</ClosedCaption>
					<NoPasses>No</NoPasses>
					<Language>English</Language>
				</Movie>
				<Movie>
					<Title>Mile 22</Title>
					<Duration>1 hr 35 min</Duration>
					<Time type="afternoon">12:05:00</Time>
					<Time type="afternoon">15:35:00</Time>
					<Time type="evening">19:25:00</Time>
					<MovieCategory>(R)</MovieCategory>
					<NewLabel>No</NewLabel>
					<ClosedCaption>No</ClosedCaption>
					<NoPasses>No</NoPasses>
					<Language>English</Language>
				</Movie>
				<Movie>
					<Title>Slender Man</Title>
					<Duration>1 hr 33 min</Duration>
					<Time type="evening">19:40:00</Time>
					<MovieCategory>(PG-13)</MovieCategory>
					<NewLabel>No</NewLabel>
					<ClosedCaption>No</ClosedCaption>
					<NoPasses>No</NoPasses>
					<Language>English</Language>
				</Movie>
				<Movie>
					<Title>The Spy Who Dumped Me</Title>
					<Duration>1 hr 56 min</Duration>
					<Time type="afternoon">14:30:00</Time>
					<MovieCategory>(R)</MovieCategory>
					<NewLabel>No</NewLabel>
					<ClosedCaption>No</ClosedCaption>
					<NoPasses>No</NoPasses>
					<Language>English</Language>
				</Movie>
			</Movies>
		</Theater>
		<Theater>
			<Name>Regal Culver Ridge Plaza 16</Name>
			<Address>
				<Street>2255 Ridge Road East</Street>
				<Zip>14622</Zip>
			</Address>
			<Note>Text to FNDGO (36346) from your wireless device to get this theater's showtimes.</Note>
			<Movies>
				<Movie>
					<Title>Life Itself (2018)</Title>
					<Duration>1 hr 58 min</Duration>
					<Time type="afternoon">13:45:00</Time>
					<Time type="evening">16:30:00</Time>
					<Time type="evening">19:15:00</Time>
					<Time type="night">22:00:00</Time>
					<MovieCategory>(R)</MovieCategory>
					<NewLabel>Yes</NewLabel>
					<ClosedCaption>Yes</ClosedCaption>
					<NoPasses>No</NoPasses>
					<Language>English</Language>
				</Movie>
				<Movie>
					<Title>The House with a Clock in its Walls</Title>
					<Duration>1 hr 45 min</Duration>
					<Time type="afternoon">14:15:00</Time>
					<Time type="evening">16:55:00</Time>
					<Time type="evening">19:45:00</Time>
					<Time type="night">22:20:00</Time>
					<MovieCategory>(PG)</MovieCategory>
					<NewLabel>Yes</NewLabel>
					<ClosedCaption>Yes</ClosedCaption>
					<NoPasses>No</NoPasses>
					<AdditionDetails>Accessibility Devices Available</AdditionDetails>
					<Language>English</Language>
				</Movie>
				<Movie>
					<Title>A Simple Favor</Title>
					<Duration>1 hr 56 min</Duration>
					<Time type="afternoon">13:20:00</Time>
					<Time type="evening">16:15:00</Time>
					<Time type="evening">19:20:00</Time>
					<Time type="night">22:05:00</Time>
					<MovieCategory>(R)</MovieCategory>
					<NewLabel>No</NewLabel>
					<ClosedCaption>Yes</ClosedCaption>
					<NoPasses>No</NoPasses>
					<AdditionDetails>Accessibility Devices Available</AdditionDetails>
					<Language>English</Language>
				</Movie>
				<Movie>
					<Title>The Predator (2018)</Title>
					<Duration>1 hr 41 min</Duration>
					<Time type="afternoon">13:30:00</Time>
					<Time type="evening">16:05:00</Time>
					<Time type="evening">19:00:00</Time>
					<Time type="night">21:40:00</Time>
					<MovieCategory>(R)</MovieCategory>
					<NewLabel>No</NewLabel>
					<ClosedCaption>Yes</ClosedCaption>
					<NoPasses>No</NoPasses>
					<AdditionDetails>Accessibility Devices Available</AdditionDetails>
					<Language>English</Language>
				</Movie>
				<Movie>
					<Title>White Boy Rick</Title>
					<Duration>1 hr 51 min</Duration>
					<Time type="afternoon">13:55:00</Time>
					<Time type="evening">16:35:00</Time>
					<Time type="evening">19:25:00</Time>
					<Time type="night">22:15:00</Time>
					<MovieCategory>(R)</MovieCategory>
					<NewLabel>Yes</NewLabel>
					<ClosedCaption>Yes</ClosedCaption>
					<NoPasses>No</NoPasses>
					<AdditionDetails>Accessibility Devices Available</AdditionDetails>
					<Language>English</Language>
				</Movie>
			</Movies>
		</Theater>
		<Theater>
			<Name>Regal Henrietta Stadium 18</Name>
			<Address>
				<Street>525 Marketplace Drive</Street>
				<Zip>14623</Zip>
			</Address>
			<Note>Text to FNDGO (36346) from your wireless device to get this theater's showtimes.</Note>
			<Movies>
				<Movie>
					<Title>Rebel Without a Cause (1955) presented by TCM</Title>
					<Duration>2 hr 5 min</Duration>
					<Time type="afternoon">14:00:00</Time>
					<Time type="evening">19:00:00</Time>
					<MovieCategory>(PG-13)</MovieCategory>
					<NewLabel>Yes</NewLabel>
					<ClosedCaption>No</ClosedCaption>
					<NoPasses>Yes</NoPasses>
					<AdditionDetails>Alternative Content</AdditionDetails>
					<Language>English</Language>
				</Movie>
				<Movie>
					<Title>Assassination Nation</Title>
					<Duration>1 hr 50 min</Duration>
					<Time type="afternoon">13:20:00</Time>
					<Time type="evening">16:30:00</Time>
					<Time type="evening">19:20:00</Time>
					<Time type="night">22:10:00</Time>
					<MovieCategory>(R)</MovieCategory>
					<NewLabel>Yes</NewLabel>
					<ClosedCaption>Yes</ClosedCaption>
					<NoPasses>No</NoPasses>
					<AdditionDetails>Accessibility Devices Available</AdditionDetails>
					<Language>English</Language>
				</Movie>
				<Movie>
					<Title>Fahrenheit 11/9</Title>
					<Duration>2 hr 6 min</Duration>
					<Time type="afternoon">15:10:00</Time>
					<Time type="evening">18:20:00</Time>
					<Time type="night">21:35:00</Time>
					<MovieCategory>(R)</MovieCategory>
					<NewLabel>Yes</NewLabel>
					<ClosedCaption>No</ClosedCaption>
					<NoPasses>No</NoPasses>
					<Language>English</Language>
				</Movie>
				<Movie>
					<Title>Life Itself (2018)</Title>
					<Duration>1 hr 58 min</Duration>
					<Time type="afternoon">13:10:00</Time>
					<Time type="evening">16:05:00</Time>
					<Time type="evening">19:00:00</Time>
					<Time type="night">21:50:00</Time>
					<MovieCategory>(R)</MovieCategory>
					<NewLabel>Yes</NewLabel>
					<ClosedCaption>Yes</ClosedCaption>
					<NoPasses>No</NoPasses>
					<Language>English</Language>
				</Movie>
				<Movie>
					<Title>The House with a Clock in its Walls</Title>
					<Duration>1 hr 45 min</Duration>
					<Time type="afternoon">12:40:00</Time>
					<Time type="afternoon">13:40:00</Time>
					<Time type="afternoon">15:30:00</Time>
					<Time type="evening">16:30:00</Time>
					<Time type="evening">18:20:00</Time>
					<Time type="evening">19:20:00</Time>
					<Time type="night">22:00:00</Time>
					<MovieCategory>(PG)</MovieCategory>
					<NewLabel>Yes</NewLabel>
					<ClosedCaption>Yes</ClosedCaption>
					<NoPasses>No</NoPasses>
					<AdditionDetails>Accessibility Devices Available</AdditionDetails>
					<Language>English</Language>
				</Movie>
			</Movies>
		</Theater>
	</Location>
</Fandango>
